// <auto-generated />
using BibliotecaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240430222408_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaApi.Models.Enuns.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataLivro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("bit");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomedoLivro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TB_LIVRO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Deus",
                            DataLivro = "Desconhecido",
                            Disponibilidade = true,
                            Genero = "Livro Sagrado",
                            NomedoLivro = "Bíblia",
                            preco = 50m
                        },
                        new
                        {
                            Id = 2,
                            Autor = "George Orwell",
                            DataLivro = "1949",
                            Disponibilidade = true,
                            Genero = "Ficção política",
                            NomedoLivro = "1984",
                            preco = 30m
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Charlie Mackesy",
                            DataLivro = "2020",
                            Disponibilidade = true,
                            Genero = "Animação",
                            NomedoLivro = "O Menino, a Toupeira, a Raposa e o Cavalo",
                            preco = 60m
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Charles Duhigg",
                            DataLivro = "2012",
                            Disponibilidade = true,
                            Genero = "Livro de autoajuda",
                            NomedoLivro = "O Poder do Hábito",
                            preco = 55m
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Christian Barbosa",
                            DataLivro = "2008",
                            Disponibilidade = true,
                            Genero = "Livro de autoajuda",
                            NomedoLivro = "A tríade do tempo",
                            preco = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
